---
title: "Tracking Hurricanes"
author: "Candice Kasahara"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
library(kableExtra)

data(world)
data(us_states)

dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"

tdir=tempdir()
download.file(dataurl, destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir) #unzip the compressed folder
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))

storms_1950 <- storm_data %>%
  filter(SEASON >= 1950) %>%
  mutate_if(is.numeric, function(x) ifelse(x==999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))

region <- st_bbox(storms_1950)
```

## Make the first plot
```{r}
ggplot(storms_1950) +
  facet_wrap(~decade) +
  stat_bin2d(data=storms_1950, aes(y=st_coordinates(storms_1950)[,2], x=st_coordinates(storms_1950)[,1]), bins=100) +
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks=c(1,10,100,1000)) +
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) +
  theme(axis.title = element_blank())
```

## Calculate table of the five states with most storms.
```{r}
x = st_transform(us_states, 4326) %>% 
  select(state=NAME)
storm_states <- st_join(storms_1950, x, join = st_intersects,left = F) %>%
  group_by(state) %>% 
  summarize(storms=length(unique(NAME))) %>% 
  arrange(desc(storms)) %>% 
  slice(1:5)%>%
  select(state, storms)

storm_states %>%
  kable(caption = 'Five states that have experienced the most storms') %>%
  kable_styling(latex_options = c("striped", "scale_down"), full_width = T, position = "left") %>%
  row_spec(1, color = "red")
```