---
title: "CS_11"
author: "Candice Kasahara"
date: '2022-11-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(spData)
library(sf)
library(foreach)
library(doParallel)
library(mapview)

registerDoParallel(4)
getDoParWorkers()
```

```{r}
library(tidycensus)
census_api_key("API Key here", install = TRUE)
```

```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)

erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T) 

```

```{r}
ec = c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
buffalo = st_crop(erie, ec)
```

```{r}
buf_block = foreach(i = unique(buffalo$variable), .combine = rbind) %do% {
  filter(buffalo,variable==i) %>%
    st_sample(size=.$value) %>%
    st_as_sf() %>%
    mutate(variable = i)}
```

```{r}
mapview(buf_block, zcol = "variable", cex = 0.1, alpha = 0)
```
